# -*- coding: utf-8 -*-
#
# sphinx_essc_geo documentation build configuration file, created by
# sphinx-quickstart on Tue May 18 09:01:35 2010.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.append(os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.ifconfig",
    "sphinx.ext.viewcode",
    "sphinx_rtd_theme",
    "sphinx.ext.imgconverter",
    "sphinx.ext.imgmath",
]
# extensions = ['rst2pdf.pdfbuilder']

pdf__documents = ["index"]
pdf_stylesheets = ["sphinx", "kerning", "a4"]
pdf_style_path = [".", "styles"]


# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix of source filenames.
source_suffix = ".rst"

# The encoding of source files.
# source_encoding = 'utf-8'

# The master toctree document.
master_doc = "index"

# General information about the project.
project = (
    "GIS Training for Southern Luzon Landscape using Free and Open Source Software"
)
copyright = "2026, https://conservation.org license under GNU Free Document License"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = "1.0"
# The full version, including alpha/beta/rc tags.
release = "1.0"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
today_fmt = "%B %d, %Y"

# List of documents that shouldn't be included in the build.
# unused_docs = ['intro.rst', 'chapter1.rst']

# List of directories, relative to source directory, that shouldn't be searched
# for source files.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", ".venv", "venv", "lib", "lib64"]

# The reST default role (used for this markup: `text`) to use for all documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []


# TODO:check for duplicate entries
rst_epilog = """

.. |mActionAddBasicShape| image:: /images/qgis_icons/mActionAddBasicShape.svg
   :width: 30pt

.. |mActionAddImage| image:: /images/qgis_icons/mActionAddImage.svg
   :width: 30pt

.. |mActionAddLegend| image:: /images/qgis_icons/mActionAddLegend.svg
   :width: 30pt

.. |mActionAddMap| image:: /images/qgis_icons/mActionAddMap.svg
   :width: 30pt

.. |mActionAddOgrLayer| image:: /images/qgis_icons/mActionAddOgrLayer.svg
   :width: 30pt

.. |mActionAddRasterLayer| image:: /images/qgis_icons/mActionAddRasterLayer.svg
   :width: 30pt

.. |mActionAddWmsLayer| image:: /images/qgis_icons/mActionAddWmsLayer.svg
   :width: 30pt

.. |mActionAlignLeft| image:: /images/qgis_icons/mActionAlignLeft.svg
   :width: 30pt

.. |mActionCalculateField| image:: /images/qgis_icons/mActionCalculateField.svg
   :width: 30pt

.. |mActionCaptureLine| image:: /images/qgis_icons/mActionCaptureLine.svg
   :width: 30pt

.. |mActionCapturePoint| image:: /images/qgis_icons/mActionCapturePoint.svg
   :width: 30pt

.. |mActionCapturePolygon| image:: /images/qgis_icons/mActionCapturePolygon.svg
   :width: 30pt

.. |mActionDeleteAttribute| image:: /images/qgis_icons/mActionDeleteAttribute.svg
   :width: 30pt

.. |mActionDeleteSelected| image:: /images/qgis_icons/mActionDeleteSelected.svg
   :width: 30pt

.. |mActionDraw| image:: /images/qgis_icons/mActionDraw.svg
   :width: 30pt

.. |mActionEditCopy| image:: /images/qgis_icons/mActionEditCopy.svg
   :width: 30pt

.. |mActionEditCut| image:: /images/qgis_icons/mActionEditCut.svg
   :width: 30pt

.. |mActionEditPaste| image:: /images/qgis_icons/mActionEditPaste.svg
   :width: 30pt

.. |mActionFileNew| image:: /images/qgis_icons/mActionFileNew.svg
   :width: 30pt

.. |mActionFilePrint| image:: /images/qgis_icons/mActionFilePrint.svg
   :width: 30pt

.. |mActionFileSave| image:: /images/qgis_icons/mActionFileSave.svg
   :width: 30pt

.. |mActionGroupItems| image:: /images/qgis_icons/mActionGroupItems.svg
   :width: 30pt

.. |mActionIdentify| image:: /images/qgis_icons/mActionIdentify.svg
   :width: 30pt

.. |mActionInvertSelection| image:: /images/qgis_icons/mActionInvertSelection.svg
   :width: 30pt

.. |mActionLabel| image:: /images/qgis_icons/mActionLabel.svg
   :width: 30pt

.. |mActionMeasureArea| image:: /images/qgis_icons/mActionMeasureArea.svg
   :width: 30pt

.. |mActionMeasure| image:: /images/qgis_icons/mActionMeasure.svg
   :width: 30pt

.. |mActionMoveFeature| image:: /images/qgis_icons/mActionMoveFeature.svg
   :width: 30pt

.. |mActionNewAttribute| image:: /images/qgis_icons/mActionNewAttribute.svg
   :width: 30pt

.. |mActionNewComposer| image:: /images/qgis_icons/mActionNewComposer.svg
   :width: 30pt

.. |mActionNewVectorLayer| image:: /images/qgis_icons/mActionNewVectorLayer.svg
   :width: 30pt

.. |mActionOptions| image:: /images/qgis_icons/mActionOptions.svg
   :width: 30pt

.. |mActionPan| image:: /images/qgis_icons/mActionPan.svg
   :width: 30pt

.. |mActionRaiseItems| image:: /images/qgis_icons/mActionRaiseItems.svg
   :width: 30pt

.. |mActionSaveAllEdits| image:: /images/qgis_icons/mActionSaveAllEdits.svg
   :width: 30pt

.. |mActionSaveAsPDF| image:: /images/qgis_icons/mActionSaveAsPDF.svg
   :width: 30pt

.. |mActionSaveMapAsImage| image:: /images/qgis_icons/mActionSaveMapAsImage.svg
   :width: 30pt

.. |mActionScaleBar| image:: /images/qgis_icons/mActionScaleBar.svg
   :width: 30pt

.. |mActionSelectPan| image:: /images/qgis_icons/mActionSelectPan.svg
   :width: 30pt

.. |mActionSelectedToTop| image:: /images/qgis_icons/mActionSelectedToTop.svg
   :width: 30pt

.. |mActionToggleEditing| image:: /images/qgis_icons/mActionToggleEditing.svg
   :width: 30pt

.. |mActionUngroupItems| image:: /images/qgis_icons/mActionUngroupItems.svg
   :width: 30pt

.. |mActionUnselectAttributes| image:: /images/qgis_icons/mActionDeselectAll.svg
   :width: 30pt

.. |mActionZoomFullExtent| image:: /images/qgis_icons/mActionZoomFullExtent.svg
   :width: 30pt

.. |mActionZoomIn| image:: /images/qgis_icons/mActionZoomIn.svg
   :width: 30pt

.. |mActionZoomLast| image:: /images/qgis_icons/mActionZoomLast.svg
   :width: 30pt

.. |mActionZoomOut| image:: /images/qgis_icons/mActionZoomOut.svg
   :width: 30pt

.. |mActionZoomToLayer| image:: /images/qgis_icons/mActionZoomToLayer.svg
   :width: 30pt

.. |mActionZoomToSelected| image:: /images/qgis_icons/mActionZoomToSelected.svg
   :width: 30pt

.. |mActionShowPluginManager| image:: /images/qgis_icons/mActionShowPluginManager.svg
   :width: 30pt

.. |mActionAddDelimitedTextLayer| image:: /images/qgis_icons/mActionAddDelimitedTextLayer.svg
   :width: 30pt

.. |mIconExpressionSelect| image:: /images/qgis_icons/mIconExpressionSelect.svg
   :width: 30pt

.. |quickmapservicesdownload| image:: /images/qgis_icons/quickmapservicesdownload.svg
   :width: 30pt
.. |georeferencer| image:: /images/qgis_icons/mGeorefRun.svg
   :width: 30pt
.. |OSM| image:: /images/qgis_icons/Openstreetmap_logo.svg
   :width: 30pt
.. |mActionAddGCPPoint| image:: images/qgis_icons/mActionAddGCPPoint.svg
   :width: 30pt
"""

# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  Major themes that come with
# Sphinx are currently 'default' and 'sphinxdoc'.
html_theme = "sphinx_rtd_theme"  #'nature'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "collapse_navigation": True,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "includehidden": True,
    "titles_only": False,
    "style_external_links": True,
    "vcs_pageview_mode": "",
    "style_nav_header_background": "white",
    # This is the key setting for width
    "prev_next_buttons_location": "bottom",
}

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = "Conservation International"

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = "CI GIS Training"

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "CI_Logo.jpg"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "CI_Logo_single.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = [
    "custom.css",
]
# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = "%b %d, %Y"

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
html_use_modindex = False

# If false, no index is generated.
html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
html_use_opensearch = ""

# If nonempty, this is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = ''

# Output file base name for HTML help builder.
htmlhelp_basename = "sphinx_CIP_geodoc"

# -- Options for rst2pdf output --------------------------------------------------
numpydoc_show_class_members = False

# Grouping the document tree into PDF files. List of tuples
# (source start file, target name, title, author, options).
#
# If there is more than one author, separate them with \\.
# For example: r'Guido van Rossum\\Fred L. Drake, Jr., editor'
#
# The options element is a dictionary that lets you override
# this config per-document.
# For example,
# ('index', u'MyProject', u'My Project', u'Author Name',
#  dict(pdf_compressed = True))
# would mean that specific document would be compressed
# regardless of the global pdf_compressed setting.

# pdf_documents = [
#        ('index', u'MyProject', u'My Project', u'Author Name'),
#    ]

# A comma-separated list of custom stylesheets. Example:
# pdf_stylesheets = ['sphinx','kerning','a4']

# Create a compressed PDF
# Use True/False or 1/0
# Example: compressed=True
# pdf_compressed = False

# A colon-separated list of folders to search for fonts. Example:
# pdf_font_path = ['/usr/share/fonts', '/usr/share/texmf-dist/fonts/']

# Language to be used for hyphenation support
# pdf_language = "en_US"

# Mode for literal blocks wider than the frame. Can be
# overflow, shrink or truncate
# pdf_fit_mode = "shrink"

# Section level that forces a break page.
# For example: 1 means top-level sections start in a new page
# 0 means disabled
# pdf_break_level = 0

# When a section starts in a new page, force it to be 'even', 'odd',
# or just use 'any'
# pdf_breakside = 'any'

# Insert footnotes where they are defined instead of
# at the end.
# pdf_inline_footnotes = True

# verbosity level. 0 1 or 2
# pdf_verbosity = 0

# If false, no index is generated.
# pdf_use_index = True

# If false, no modindex is generated.
# pdf_use_modindex = True

# If false, no coverpage is generated.
# pdf_use_coverpage = True

# Name of the cover page template to use
# pdf_cover_template = 'sphinxcover.tmpl'

# Documents to append as an appendix to all manuals.
# pdf_appendices = []

# Enable experimental feature to split table cells. Use it
# if you get "DelayedTable too big" errors
# pdf_splittables = False

# Set the default DPI for images
# pdf_default_dpi = 72

# Enable rst2pdf extension modules (default is only vectorpdf)
# you need vectorpdf if you want to use sphinx's graphviz support
# pdf_extensions = ['vectorpdf']

# Page template name for "regular" pages
# pdf_page_template = 'cutePage'

# Show Table Of Contents at the beginning?
# pdf_use_toc = True

# How many levels deep should the table of contents be?
# pdf_toc_depth = 9999

# Add section number to section references
# pdf_use_numbered_links = False

# Background images fitting mode
# pdf_fit_background_mode = 'scale'

# -- Options for LaTeX output --------------------------------------------------

# The paper size ('letter' or 'a4').
latex_paper_size = "a4"

# The font size ('10pt', '11pt' or '12pt').
# latex_font_size = '10pt'

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
    (
        "index",
        "ESSCFOSSGeo.tex",
        "ADDU-TROPICS ESSC MTRM FOSS-Geo Materials SY 2011-2012",
        "ESSC",
        "manual",
        "False",
    ),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = "essclogotrace_thumbnail.jpg"

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
latex_use_parts = False

# Additional stuff for the LaTeX preamble.

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_use_modindex = True

# If true, add page references after internal references. This is very useful for printed copies of the manual. Default is False.
latex_show_pageref = True

# Control whether to display URL addresses. This is very useful for printed copies of the manual. The setting can have the following values:  'no' – do not display URLs (default); 'footnote' – display URLs in footnotes; 'inline' – display URLs inline in parentheses
# latex_show_urls = True

latex_elements = {
    "classoptions": ",openany,oneside",
    "babel": "\\usepackage[english]{babel}",
}


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "python": ("https://docs.python.org/", None),
}


# edit checks
todo_include_todos = True
